global:
  dockerBase: "us-west1-docker.pkg.dev/zerok-dev/zk-client"

kubernetesClusterDomain: cluster.local
zkGpt:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  replicas: 1
  type: ClusterIP
  resources:
    limits:
      cpu: 500m
      memory: 1Gi

axon:
  host: ""

postgres:
  host: ""
  user: ""
  port: ""
  db: ""
  pass: ""

redis: 
  host: ""
  port: ""

pinecone:
  environment: ""
  apikey: "" 
  indexkey: "" 

maxspanrawdatalength: 1000

openai:
  apikey: ""

replicaCount: 1
image:
  repo: "zk-gpt"
  tag: latest
  pullPolicy: IfNotPresent

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80