global:
  dockerBase: "us-west1-docker.pkg.dev/zerok-dev/zk-client"

kubernetesClusterDomain: cluster.local
zkGpt:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  replicas: 1
  type: ClusterIP
  resources:
    limits:
      cpu: 500m
      memory: 1Gi

axon:
  host: "zk-axon.zk-client.svc.cluster.local"

wsp:
  host: "http://zk-wsp-client.zk-client.svc.cluster.local"

zkSlack:
  host: "http://zk-slack.zkcloud.svc.cluster.local:80/i/slack/publish/inference"



initImage:
  repo: "us-west1-docker.pkg.dev/black-scope-358204/zk-client/prod/curl"
  tag: latest

postgres:
  host: "postgres.zk-client.svc.cluster.local"
  user: "postgres"
  port: "5432"
  db: "gpt"
  password: ""

redis: 
  host: "redis-master.zk-client.svc.cluster.local"
  port: "6379"
  password: ""

pinecone:
  environment: ""
  apikey: "" 
  index: "" 

maxspanrawdatalength: 1000

openai:
  apikey: ""

replicaCount: 1
image:
  repo: "zk-gpt"
  tag: latest
  pullPolicy: IfNotPresent

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80