global:
  dockerBase: "us-west1-docker.pkg.dev/zerok-dev/zk-client"

kubernetesClusterDomain: cluster.local
zkGpt:
  configYaml: |-
    host: "zk-axon.zk-client.svc.cluster.local:80"
    openai_key: "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"
    max_span_raw_data_length: 1000
    redis_host: "redis-master.zk-client.svc.cluster.local"
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  replicas: 1
  type: ClusterIP
  zkGpt:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi


image:
  repo: "zk-gpt"
  tag: latest
  imagePullPolicy: Always