apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-gpt
data:
  config.yaml: |-
    host: "zk-axon.zk-client.svc.cluster.local:80"
    openai_key: "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"
