redis_host: localhost
redis_password:
openai_key: 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
max_span_raw_data_length: 1000
postgres_host: localhost
pinecone_key: cc77b1e4-3ec0-4b4f-a3eb-93453e1c43c2
pinecone_index: zk-index-prod
axon_host: localhost:8080
pinecone_env: us-west4-gcp-free
postgres_port: 5101
postgres_db: gpt
postgres_user: postgres
postgres_password: eo1Mgtm6HI
wsp_host: http://localhost:8987/request
zk_slack_host: http://zk-slack.zkcloud.svc.cluster.local:80/v1/i/slack/publish/inference
clusterId: 56d95a4d-47e6-4acb-88cd-2588df9b6176
