name: build-push
on:
  workflow_call:
    inputs:
      VERSION:
        type: string
        default: 'latest'
      ENVIRONMENT:
        type: string
        default: 'poc'
      DOCKER_IDENTIFIER:
        type: string
        default: 'prod'
    secrets:
      GKE_SA_KEY:
        required: true
env:
  ENV: ${{ github.event.inputs.ENV }}
  DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  DOCKER_REG: ${{ vars.DOCKER_REG }}
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  DOCKER_REPO: ${{ vars.DOCKER_REPO }}
  APP_NAME: ${{ vars.APP_NAME }}
  TOKEN: ${{ secrets.GITPAT }}
  VERSION: ${{ inputs.VERSION }}
  ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  DOCKER_IDENTIFIER: ${{ inputs.DOCKER_IDENTIFIER }}
  POSTGRES_PASSWORD:  ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_DB: ${{ vars.POSTGRES_DB }}
  POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
  POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
  REDIS_HOST: ${{ vars.REDIS_HOST }}
  GKE_CLUSTER: ${{ github.event.inputs.GKE_CLUSTER }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_ZONE : ${{ vars.GKE_ZONE }}
  PINECONE_INDEX_KEY: ${{ secrets.PINECONE_INDEX_KEY }}
  PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
  PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
  OPENAPI_KEY: ${{ secrets.OPENAPI_KEY }}

jobs:
  print-envs:
    runs-on: zk-self-hosted
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Check output
        run: |
          echo "GIT_TAG=$GIT_TAG"
          echo "DOCKER_TAG=$VERSION"
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "DOCKER_REPO=$DOCKER_REPO"
          echo "ENVIRONMENT=$ENVIRONMENT"

  ##############
  docker-build:
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    runs-on: zk-self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GKE_SA_KEY }}'

      - name: login to docker registry
        run: |
          gcloud auth configure-docker $DOCKER_REG --quiet
          
      - name: Docker build
        run: |-
          echo "DOCKER_TAG=$VERSION"
          docker build  --tag "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$GITHUB_SHA" .

      - name: Docker Tag
        run: |-
          echo "DOCKER_TAG=$VERSION"
          docker tag "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$GITHUB_SHA" "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$VERSION"

      - name: Docker push
        run: |-
          echo "DOCKER_TAG=$VERSION"
          docker push "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$GITHUB_SHA"
          docker push "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$VERSION"
